CREATE WAREHOUSE IF NOT EXISTS ETL_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;


-- schemas
CREATE DATABASE IF NOT EXISTS RETAIL_DB

CREATE OR REPLACE SCHEMA STAGING_LAYER;
CREATE OR REPLACE SCHEMA CLEANSED;
CREATE OR REPLACE SCHEMA BUSINESS;
CREATE OR REPLACE SCHEMA PRESENTATION;

CREATE OR REPLACE FILE FORMAT RETAIL_DB.STAGING_LAYER.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;

CREATE OR REPLACE STAGE RETAIL_DB.STAGING_LAYER.RETAIL_S3_STAGE
    URL = 's3://data-warehouse-course1/exam_output/'
    CREDENTIALS =(
        AWS_KEY_ID = 'env_AWS_KEY_ID',
        AWS_SECRET_KEY = 'env_AWS_SECRET_KEY'
        )
    FILE_FORMAT = RETAIL_DB.STAGING_LAYER.CSV_FORMAT;

CREATE OR REPLACE TABLE RETAIL_DB.CLEANSED.CLEANED_SALES(
    sales_id INT,
    product_id INT,
    region STRING,
    qty INT,
    price NUMERIC(10,2),
    time_stamp DATE,
    discount NUMERIC(10,2),
    order_status STRING
);





COPY INTO RETAIL_DB.CLEANSED.CLEANED_SALES
FROM @RETAIL_DB.STAGING_LAYER.RETAIL_S3_STAGE/
FILES = ('cleaned_sales.csv')
FILE_FORMAT = (FORMAT_NAME = RETAIL_DB.STAGING_LAYER.CSV_FORMAT)
ON_ERROR = 'CONTINUE'

SELECT * FROM RETAIL_DB.CLEANSED.CLEANED_SALES  

    
CREATE OR REPLACE TABLE RETAIL_DB.CLEANSED.CLEANED_PRODUCTS (
  product_id INT,
  category STRING,
  brand STRING,
  rating FLOAT,
  in_stock BOOLEAN,
  launch_date DATE
);

COPY INTO RETAIL_DB.CLEANSED.CLEANED_PRODUCTS
  FROM @RETAIL_DB.STAGING_LAYER.RETAIL_S3_STAGE/cleaned_products.csv
  FILE_FORMAT = (FORMAT_NAME = RETAIL_DB.STAGING_LAYER.CSV_FORMAT)
  ON_ERROR = 'CONTINUE';

--SELECT * FROM RETAIL_DB.CLEANSED.CLEANED_PRODUCTS  

CREATE OR REPLACE TABLE RETAIL_DB.CLEANSED.MERGED_SALES_PRODUCTS (
  sales_id INT,
  product_id INT,
  region STRING,
  qty INT,
  price NUMERIC(10, 2),
  time_stamp DATE,
  discount NUMERIC(10, 2),
  order_status STRING,
  category STRING,
  brand STRING,
  rating FLOAT,
  in_stock BOOLEAN,
  launch_date DATE
);

COPY INTO RETAIL_DB.CLEANSED.MERGED_SALES_PRODUCTS
  FROM @RETAIL_DB.STAGING_LAYER.RETAIL_S3_STAGE/merged_sales_products.csv
  FILE_FORMAT = (FORMAT_NAME = RETAIL_DB.STAGING_LAYER.CSV_FORMAT)
  ON_ERROR = 'CONTINUE';

--SELECT * FROM RETAIL_DB.CLEANSED.MERGED_SALES_PRODUCTS  




--analytics

CREATE OR REPLACE TABLE RETAIL_DB.BUSINESS.DIM_PRODUCT AS
SELECT DISTINCT
  product_id,
  category,
  brand,
  rating,
  in_stock,
  launch_date
FROM RETAIL_DB.CLEANSED.MERGED_SALES_PRODUCTS;

SELECT * FROM RETAIL_DB.BUSINESS.DIM_PRODUCT



CREATE OR REPLACE TABLE RETAIL_DB.BUSINESS.DIM_DATE AS
SELECT DISTINCT
  time_stamp AS date_key,
  YEAR(time_stamp) AS year_number,
  QUARTER(time_stamp) AS quarter_number,
  MONTH(time_stamp) AS month_number,
  DAY(time_stamp) AS day_number
FROM RETAIL_DB.CLEANSED.MERGED_SALES_PRODUCTS;

CREATE OR REPLACE TABLE RETAIL_DB.BUSINESS.FACT_SALES AS
SELECT
  sales_id,
  product_id,
  region,
  qty,
  price,
  discount,
  order_status,
  qty * price AS gross_revenue,
  qty * price * (1 - COALESCE(discount, 0) / 100) AS net_revenue,
  time_stamp AS date_key
FROM RETAIL_DB.CLEANSED.MERGED_SALES_PRODUCTS;

CREATE OR REPLACE TABLE RETAIL_DB.BUSINESS.AGG_REGION_MONTH AS
SELECT
  region,
  DATE_TRUNC('MONTH', time_stamp) AS month_start,
  SUM(qty) AS total_qty,
  SUM(qty * price) AS total_gross_revenue,
  SUM(qty * price * (1 - COALESCE(discount, 0) / 100)) AS total_net_revenue
FROM RETAIL_DB.CLEANSED.MERGED_SALES_PRODUCTS
GROUP BY region, month_start;

CREATE OR REPLACE TABLE RETAIL_DB.BUSINESS.AGG_CATEGORY_PERFORMANCE AS
SELECT
  category,
  SUM(qty) AS total_qty,
  SUM(qty * price * (1 - COALESCE(discount, 0) / 100)) AS total_revenue,
  AVG(rating) AS avg_rating
FROM RETAIL_DB.CLEANSED.MERGED_SALES_PRODUCTS
GROUP BY category;



--presentation
--sales per region view

CREATE OR REPLACE VIEW RETAIL_DB.PRESENTATION.VW_SALES_BY_REGION_MONTH AS
SELECT
  region,
  DATE_TRUNC('MONTH', date_key) AS month_start,
  SUM(net_revenue) AS total_revenue,
  SUM(qty) AS total_qty
FROM RETAIL_DB.BUSINESS.FACT_SALES
GROUP BY region, month_start;

USE DATABASE RETAIL_DB;
USE SCHEMA PRESENTATION;
SHOW VIEWS;
SELECT * FROM VW_SALES_BY_REGION_MONTH LIMIT 5;


-- top products view
CREATE OR REPLACE VIEW RETAIL_DB.PRESENTATION.VW_TOP_PRODUCTS AS
SELECT
  product_id,
  SUM(net_revenue) AS total_revenue,
  SUM(qty) AS total_qty
FROM RETAIL_DB.BUSINESS.FACT_SALES
GROUP BY product_id;

USE DATABASE RETAIL_DB;
USE SCHEMA PRESENTATION;
SHOW VIEWS;
SELECT * FROM VW_TOP_PRODUCTS LIMIT 5;


--revenue view
CREATE OR REPLACE VIEW RETAIL_DB.PRESENTATION.VW_REVENUE_TREND AS
SELECT
  DATE_TRUNC('MONTH', date_key) AS month_start,
  SUM(gross_revenue) AS gross_revenue,
  SUM(net_revenue) AS net_revenue
FROM RETAIL_DB.BUSINESS.FACT_SALES
GROUP BY month_start;


USE DATABASE RETAIL_DB;
USE SCHEMA PRESENTATION;
SHOW VIEWS;
SELECT * FROM VW_REVENUE_TREND LIMIT 5;


-- category performance view
CREATE OR REPLACE VIEW RETAIL_DB.PRESENTATION.VW_CATEGORY_PERFORMANCE AS
SELECT
  p.category,
  SUM(f.net_revenue) AS total_revenue,
  SUM(f.qty) AS total_qty
FROM RETAIL_DB.BUSINESS.FACT_SALES f
JOIN RETAIL_DB.BUSINESS.DIM_PRODUCT p USING (product_id)
GROUP BY p.category;


USE DATABASE RETAIL_DB;
USE SCHEMA PRESENTATION;
SHOW VIEWS;
SELECT * FROM VW_CATEGORY_PERFORMANCE LIMIT 5;

